sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: gd9TWuQdaWfz/asMKpCsQ6iNtlsw1pJzuv+e66fDSYgg0ILEYq0iY3id5JAVWovzl9ztnAba3RXNaxMORQW5nuQXiuohgz3Bao9f+b+Z9wIVUrknXJEY0F2aFJYuQj9LZaaIVDUj249Sl0nCq5IvoCBvWWDuQ6ZeIpRM1gfBaTqwSYYNAmo2EvjmntrfEQSEQnO6mgXZJnywYUdgEypSMz0eXDUb5zUwGRhMsiUoSxfR2tXq8XfKvGmq3/NJdxayC8ujxIeHoYjXb+tUuRbV3ry00N1bJt5B6vKTMCL3CS5a7qTuBQ+Y6Riw6WwyxjTH3bvmczUEbcumULIZOlv8x9InqWWLj0eGXiN2VI51Z+J0Fo05IwE7U1BxCR8aUZHiOR1aHDP0tiRbeHolgtV/+j0m2CCVz+BbE09I1Q8/AuBPpx9lZy4k3/K1q8b5Qw6HH6dj7CGFdwY0qwdqZ13Qksf8LzdeTQpuSvTOJ/e6JPucQLut+S5nWazC6kc5CHFpv2oixkxRkckMsXiEYOVMMoQEc9uftj+Og1+/Y3OtYD/k8xGWp+V/mZifBrin0aaer/E20dJuJIePRhb5SiBzh4pgLMQjNJXlcwxsXys96jnO+vig2tUhY+n8RdrOPxr/8mPCUyWI7klbOS25sxGykGnAJTr1tfwNZdAtfgjLF+0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Beethoven-the-Man-and-the-Artist-as-Revealed-in-His-Own-Words_3528
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy